version: '3.9'
services:
    db:
        restart: always
        container_name: db
        image: mysql:8.0.27
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "${MYSQL_PORT}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ./db:/var/lib/mysql

    php:
        restart: always
        container_name: php-fpm
        build:
            context: ./php-fpm
            args:
                PHP_XDEBUG_MODE: ${PHP_XDEBUG_MODE}
                PHP_XDEBUG_CLIENT_PORT: ${PHP_XDEBUG_CLIENT_PORT}
                PHP_XDEBUG_CLIENT_HOST: ${PHP_XDEBUG_CLIENT_HOST}
                SYMFONY_CLI_VERSION: 4.27.4
        ports:
            - "${PHP_PORT}:9001"
        volumes:
            - ./app:/var/www/app:cached
            - ./logs/app:/var/www/app/var/log:cached
        depends_on:
            - db

    nginx:
        restart: always
        container_name: nginx
        build: 
            context: ./nginx
            args:
                NGINX_SERVER_NAME: ${NGINX_SERVER_NAME}
        ports:
            - "${NGINX_PORT}:80"
        depends_on:
            - php
        environment:
            - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
            - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/templates
            - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.template
            - NGINX_SERVER_NAME=${NGINX_SERVER_NAME}
        volumes:
            - ./logs/nginx:/var/log/nginx:cached
            - ./app:/var/www/app:cached
